### ISSUE TITLE
The Input of HERA?

### ISSUE THREAD

**Issue by yxgz** [RomeroBarata/hierarchical_action_prediction#1]
Hi, thank you for the great project. 
Does the input of HERA contain only text information (label and duration of action) without visual information (visual features of action) ?
Thank you!

**Comment by RomeroBarata** [comment]
Hi,

You are right, the input for HERA is just the label of the action (one-hot encoding) and its duration (as a proportion in relation to the parent level).

Kind regards,
Romero
